version: '3'

services:
  db:
    image: postgres:13.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: nata
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: study_db
    ports:
      - 5432:5432

